# Generated by Django 2.2.6 on 2019-12-07 05:06

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dt_content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blurb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=256, unique=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('plain_text', models.BooleanField(default=False, editable=False)),
                ('last_known_location', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='blurb',
            index=models.Index(fields=['identifier'], name='dt_content__identif_a63e57_idx'),
        ),
        migrations.AddIndex(
            model_name='blurb',
            index=models.Index(fields=['last_known_location', 'identifier'], name='dt_content__last_kn_1368e9_idx'),
        ),
    ]
