# Generated by Django 2.2.6 on 2019-12-29 00:14

from django.db import migrations
import dt_content.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dt_content', '0002_auto_20191207_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blurb',
            name='content',
            field=dt_content.fields.SummernoteField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='richtextblock',
            name='content',
            field=dt_content.fields.SummernoteField(blank=True, default=''),
        ),
    ]
