# Generated by Django 2.2.6 on 2019-12-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dt_content', '0003_auto_20191229_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='blurb',
            name='label',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blurb',
            name='identifier',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='blurb',
            name='last_known_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
