# Generated by Django 2.2.2 on 2019-07-12 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blurb",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=512, unique=True)),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="content"),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="blurb",
            index=models.Index(
                fields=["identifier"], name="blurb_blurb_identif_ed19b4_idx"
            ),
        ),
    ]
