# Generated by Django 2.2.4 on 2019-09-04 03:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blurb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blurb',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='content'),
        ),
    ]
