# Generated by Django 2.2.6 on 2019-12-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blurb', '0002_auto_20190904_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='blurb',
            name='plain',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
